README.md
This PR updates, removes and modify outdated packages, It also improves the guidelines.
There were a lot of changes so I put them all in this PR
=> update/remove/modify outdated packages, improve guidelines

README.md
Shamelessly self-promoting CrossDart tools. But they are really awesome, I promise.
Crossdart allows you to navigate through the code of the whole Dart ecosystem, and great as a learning tool. And Crossdart Chrome Extension is very useful for the teams, which practice code reviews.
=> Add Crossdart

README.md
The Cassowary package is actively maintained and used within Sky, and is pretty awesome for UI's :)
I also want to see more algorithms / data structures in the future, so I created a separate section.
FYI @yissachar
=> Add algorithms section and cassowary

README.md
Info about plugin for Visual Studio Code has been added.
=> Add dart code plugin for visual studio code

README.md
Revise Client Web Framework section
=> Revise section for AngularDart and Flutter, Closes #43

README.md
https://workiva.github.io/over_react/
@yissachar 😄
=> Added OverReact to Client Web App Frameworks list

README.md
I wrote a detailed tutorial about getting started with Dart & React creating a todo list. Let me know what you think 😄
=> Add tutorial for Dart & React

README.md
Also, sort "utilities".
Popularity/health/maintenance:
https://pub.dartlang.org/packages/built_value#-analysis-tab-
=> Add built_value

README.md
Figured I would update the description to fit the main draw of flutter.
=> Revise Flutter description

README.md
This is a pretty feature rich game engine made for Flutter.
It's being maintained pretty well and is pretty popular, judging by the [analysis](https://pub.dartlang.org/packages/flame#-analysis-tab-) done in the package manager website, and also has 200+ stars in Github, which not many Dart libraries do.
=> Adding Flame game engine to the list

README.md
VueJS is pretty popular, and so, VueDart deserves to be added here.
=> Adding VueDart to the list

README.md
I went ahead and made a (hopefully) simple dependency injection container which can be used to register singletons, lazy singletons and factories with optional names and parameters.
I'm sharing here in hopes it will be useful for the Dart community. This is especially useful for Flutter, where mirrors are disabled.
=> Added dependencies package

README.md
=> Flutter Web

README.md
The Dart VSCode plugin is super well supported, used, and useful. Since all the other major IDEs are here, I thought I'd throw in a link to it. 
Also, I added punctuation to unpunctuated sentences, and spellchecked the readme :)
* I hope it's okay I split this from my other PR (#74) I just figured my changes would be clearer separate, but if you'd like I'm happy to combine them into one PR :)
=> Add VSCode Plugin

README.md
Add Community of Dart for Web development in Indonesian Language (Bahasa Indonesia).
=> Add Community of Dart for Web (id-ID)

README.md
https://pub.dev/packages/sentry
https://pub.dev/packages/sentry_flutter
https://github.com/getsentry/sentry-dart
=> Add Sentry

README.md
Dart Code Metrics is a static analysis tool that helps developers analyse and improve their code quality.
* Reports code metrics
* Provides additional rules for the analyzer
* Checks for anti-patterns
=> Add Dart Code Metrics linter

README.md
Addresses #107. Vuedart is removed because of inactivity of the project.
=> Remove vuedart due to non-maintenance

README.md
This package provides to users an easiest way to create and use isolates as a separated classes which can contain any kind of complex logic and also your separated isolates can easilly communicates with each otehrs.
=> Add Isolator package

README.md
Add [spec](https://pub.dev/packages/spec) testing package
=> feat: add spec package under testing
